sudo: false
language: rust

env:
  global:
    - CRATE=little

matrix:
  allow_failures:
    - rust: nightly
  include:
    - rust: nightly
      env: FEATURES=nightly DOC=true
    - rust: nightly
      env: FEATURES=''
    - rust: beta
      env: FEATURES=''
    - rust: stable
      env: FEATURES=''
    - rust: 1.2.0
      env: FEATURES=''
    - rust: 1.1.0
      env: FEATURES=''
    - rust: 1.0.0
      env: FEATURES=''
script:
  - cargo test --features "$FEATURES"

after_success:
  - /bin/bash export_doc.sh
